### ISSUE TITLE
Compactness

### ISSUE THREAD

**Issue by cmcmA20** [cmcmA20/cubical-mini#18]
- [x] [Π-compact](https://www.cs.bham.ac.uk/~mhe/TypeTopology/TypeTopology.CompactTypes.html#22173) types are called [exhaustible](https://github.com/cmcmA20/cubical-mini/blob/master/src/Correspondences/Exhaustible.agda) here
- [x] [∃-compact](https://www.cs.bham.ac.uk/~mhe/TypeTopology/TypeTopology.CompactTypes.html#26305) types are called [omniscient₁](https://github.com/cmcmA20/cubical-mini/blob/master/src/Correspondences/Omniscient.agda) here
- [x] [Σ-compact](https://www.cs.bham.ac.uk//~mhe/TypeTopology/TypeTopology.CompactTypes.html#20199) types done

**Comment by cmcmA20** [comment]
- [ ] Σ-compact implies decidable total order
